package(default_visibility = ["//visibility:public"])

java_library(
  name = 'amqp-client',
  exports = ["@amqp-client//jar"],
)

java_library(
  name = 'guice-multibindings',
  exports = ["@guice-multibindings//jar"],
)
