include_defs('//bucklets/maven_jar.bucklet')

VER = '2.11.8'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = 'e56d492428d0ae80224f6e3a47b3f53dfa0c7d22',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)
