include_defs('//bucklets/maven_jar.bucklet')

VER = '2.11.7'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = 'e49e930c5c4ce74fc2c4c1cde1ddfb3ff77d0d63',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)
